"""Catalyst → ToM: to samo ćwiczenie pod inną nazwą (ręcznie, ponad dokładne
dopasowania kluczem kanonicznym). Film Catalyst dołącza wtedy jako poradnik
do ćwiczenia z filmem ToM. Warianty (z bloków, z zawieszenia, z pauzą, inny
sprzęt) zostają osobnymi ćwiczeniami."""
CAT_TOM = {
    "Wide-Grip Lat Pulldown": "Lat Pulldown - Wide Grip",
    "Power Clean – Push Press": "BB Power Clean to Push Press",
    "Dumbbell Overhead Tricep Extension": "DB Overhead Triceps Extension",
    "Seated Good Morning": "BB Seated Good Morning",
    "Power Clean – Power Jerk": "BB Power Clean to Power Jerk",
    "Hang Muscle Clean": "BB Hang Muscle Clean",
    "RNT Split Squat": "Split Squat with Band RNT",
    "Dumbbell Front Raise": "2DB Front Raise",
    "Good Morning": "BB Good Morning",
    "Clean & Jerk": "BB Clean and Jerk",
    "Clean-Jerk": "BB Clean and Jerk",
    "Split Jerk": "BB Split Jerk",
    "Power Jerk": "BB Power Jerk",
    "Squat Vertical Jump": "Squat Jump",
    "Overhead Squat": "BB Overhead Squat",
    "Snatch Press": "BTN Snatch Press",
    "Press in Split": "BB Split Press",
    "Ab Rollout": "Ab Wheel Rollout",
    "Staggered RDL": "BB Staggered RDL",
    "Nordic Curl": "Nordic Hamstring Curl",
    "Concentration Curl": "Single Arm DB Concentration Curl",
    "Dumbbell Skullcrusher": "2DB Skull Crusher",
    "Z-Press": "Barbell Z Press",
    "Dumbbell Reverse Curl": "2DB Reverse Grip Curl",
    "Overhead Lateral Raise": "2DB Overhead Lateral Raise",
    "Straight-Arm Pulldown": "Band/Cable Straight Arm Lat Pulldown",
    "Standing Banded Hip Adduction": "Standing Band Hip Adduction",
    "Plank": "Front Plank",
    "Reverse-Grip Lat Pulldown": "Lat Pulldown - Hands Supinated",
    "Skullcrusher": "BB Skull Crusher",
    "Tate Press": "2DB Tate Press",
    "Bulgarian Split Squat": "Rear Foot Elevated Split Squat",
    "Power Snatch Into Overhead Squat": "BB Power Snatch to Overhead Squat",
    "Clamshell": "Side Lying Clamshell",
    "Hanging Leg Raise (HLR)": "Hanging Straight Leg Raise",
    "Reverse-Grip Low Cable Row": "2 Handed Underhand Grip Low Cable Row",
    "Flutter Kick": "Flutter Kicks",
    "Pallof Press": "Band/Cable Standing Anti Rotation Press",
    "Pause Back Squat": "BB Paused Back Squat",
}
