"""Ćwiczenia BAZY 5.17, które są w bibliotekach — ręcznie, tylko pewne dopasowania.

Klucz: id z BAZY. Wartość: (tytuły ToM, nazwy Catalyst). Tytuły ToM przechodzą
przez kanon() — trafiają w grupę z wszystkimi duplikatami nagrania.
Ogólne nazwy z BAZY (np. „Lateral raises”, „Dumbbell row”, „Calf raises”)
bez dopasowania: wariant w bibliotece może nie być tym, który trener ma na myśli.
SLDL w BAZIE to martwy ciąg na prostych nogach (nie jednonóż — EX-0018 nie jest
jednostronne), więc nie łączy się z „Single Leg Deadlift”.
"""
MAPA = {
    "EX-0001": (["Hip Abductor Machine"], []),
    "EX-0002": (["Hip Adductor Machine"], []),
    "EX-0004": (["2DB Arnold Press"], ["Arnold Press"]),
    "EX-0007": (["45 Degree Back Extension"], ["Back Extension"]),
    "EX-0009": (["Band Assisted Pull Up"], []),
    "EX-0010": (["BB High Bar Back Squat", "BB High Bar Squat"], ["Back Squat"]),
    "EX-0011": (["BB Bench Press"], ["Bench Press"]),
    "EX-0012": (["BB Curl"], []),
    "EX-0013": (["BB Low Bar Squat", "BB Low Bar Back Squat"], []),
    "EX-0014": (["BB Military Press"], ["Press"]),
    "EX-0016": (["BB Bent Over Row Overhand Grip"], ["Bent Row"]),
    "EX-0018": (["BB Stiff-Legged Deadlift"], ["Stiff-Legged Deadlift (SLDL)"]),
    "EX-0019": (["2-Arm Band/Cable Bayesian Curl"], []),
    "EX-0022": (["BB Paused Bench Press"], []),
    "EX-0029": ([], ["Hammer Curl"]),
    "EX-0036": (["Box Jump"], ["Box Jump"]),
    "EX-0039": ([], ["Cable Curl"]),
    "EX-0040": (["Cable Crossover Flye"], []),
    "EX-0041": (["Band/Cable Single Arm Lateral Raise"], []),
    "EX-0042": (["Seated Cable Row"], ["Low Cable Row"]),
    "EX-0043": (["Single Arm Low Cable Row"], []),
    "EX-0045": (["Pec Dec Machine"], []),
    "EX-0046": (["BB Clean", "Clean"], ["Clean"]),
    "EX-0047": ([], ["Block Clean"]),
    "EX-0048": ([], ["Copenhagen Plank"]),
    "EX-0051": (["BB Deadstart Row"], []),
    "EX-0053": (["Conventional Deadlift"], ["Deadlift"]),
    "EX-0204": (["BB Sumo Deadlift", "Sumo Deadlift"], []),
    "EX-0055": (["2DB Deficit Reverse Lunge"], []),
    "EX-0056": ([], ["Dip"]),
    "EX-0059": (["2DB Bench Press"], []),
    "EX-0060": (["Alternating 2DB Bench Press"], []),
    "EX-0061": (["2DB Biceps Curl"], ["Dumbbell Curl"]),
    "EX-0063": (["2DB Spider Curl"], ["Dumbbell Spider Curl"]),
    "EX-0064": (["2DB Bench Flyes"], []),
    "EX-0069": (["2DB Lateral Raise"], ["Dumbbell Lateral Raise"]),
    "EX-0080": (["Single Arm DB Bench Supported Row"], ["Single-Arm Dumbbell Row"]),
    "EX-0083": (["Pull Up Negatives"], []),
    "EX-0086": ([], ["EZ Curl"]),
    "EX-0088": (["2DB Front Foot Elevated Split Squat"], []),
    "EX-0089": (["BB Front Squat"], ["Front Squat"]),
    "EX-0090": ([], ["GHD Sit-up"]),
    "EX-0094": (["Half Kneeling Single Arm Cable or Band Pulldown"], []),
    "EX-0095": ([], ["Half-Kneeling Cross Chop"]),
    "EX-0101": (["Band/Cable SL Hip Flexion"], []),
    "EX-0102": (["BB Hip Thrust"], ["Bench-Supported Glute Bridge (Hip Thrust)"]),
    "EX-0104": (["Broad Jump"], ["Broad Jump"]),
    "EX-0105": (["Incline Bench SA DB Side Lying Lateral Raise"], []),
    "EX-0140": (["Incline Bench SA DB Side Lying Lateral Raise"], []),
    "EX-0107": (["2DB Incline Curls"], ["Incline Dumbbell Curl"]),
    "EX-0110": (["2DB Incline Flyes"], []),
    "EX-0111": (["2DB Incline Bench Press"], ["Dumbbell Incline Bench Press"]),
    "EX-0112": (["2DB Alternating Incline Bench Press"], []),
    "EX-0113": ([], ["Decline Sit-Up"]),
    "EX-0120": (["Leg Extension Machine"], ["Leg Extension"]),
    "EX-0128": (["Lat Pulldown"], ["Lat Pulldown"]),
    "EX-0130": ([], ["Single-Arm Pulldown"]),
    "EX-0131": (["Single Arm DB Lateral Raise"], []),
    "EX-0145": (["Angled BB Meadows Row"], []),
    "EX-0146": (["MB Floor Slams"], []),
    "EX-0154": ([], ["Poliquin Step-Up"]),
    "EX-0158": (["Pull-Up"], ["Pull-up"]),
    "EX-0165": (["BB Push Press"], ["Push Press"]),
    "EX-0166": (["Pushup"], ["Push-Up"]),
    "EX-0168": (["BB Romanian Deadlift"], ["Romanian Deadlift (RDL)"]),
    "EX-0170": ([], ["Rope Tricep Pushdown"]),
    "EX-0175": (["Shoulders Elevated Single Leg Hip Thrust"], ["Single-Leg Bench-Supported Glute Bridge"]),
    "EX-0179": (["2DB Seesaw Press"], []),
    "EX-0181": (["Side Plank Hip Dips"], []),
    "EX-0184": ([], ["Split Squat"]),
    "EX-0188": (["Suitcase Carry"], ["Single-Arm Farmer Carry"]),
    "EX-0190": (["Stability Ball Hamstring Curl"], []),
    "EX-0192": (["Trap Bar Deadlift"], []),
    "EX-0194": ([], ["Tricep Pushdown"]),
    "EX-0195": (["BB JM Press"], ["JM Press"]),
    "EX-0196": ([], ["Cable Overhead Tricep Extension"]),
}
