// PLIK GENEROWANY — nie edytuj recznie.
// Zrodlo: docs/dane/baza-cwiczen.json (MasterTemplate 5.17, zakladka BAZA)
// Regeneracja: python3 silnik/narzedzia/generuj-dane.py

import type { Cwiczenie } from "../typy.ts";

/** 164 cwiczen z BAZY 5.17. */
export const BAZA_CWICZEN: readonly Cwiczenie[] = [
  { id: "EX-0001", nazwa: "Abduction machine", kategoria: "Lower pull", part: "d", coeff: 0.25, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/H98IP8rARy4", scaloneId: "EX-0098" },
  { id: "EX-0002", nazwa: "Adduction machine", kategoria: "Lower push", part: "s", coeff: 0.25, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/CjAVezAggkI", scaloneId: "EX-0099" },
  { id: "EX-0003", nazwa: "Allah", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/TlUvzP3o2L4" },
  { id: "EX-0004", nazwa: "Arnold press", kategoria: "Upper push vertical", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/jeJttN2EWCo", scaloneId: "EX-0058" },
  { id: "EX-0005", nazwa: "Arnold press alternating", kategoria: "Upper push vertical", part: "b", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0006", nazwa: "B/l dragonflag eccentric", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/Ut9NKB8jPq4", scaloneId: "EX-0006x" },
  { id: "EX-0007", nazwa: "Back extension", kategoria: "Lower pull", part: "d", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/ph3pddpKzzw" },
  { id: "EX-0008", nazwa: "Banded pistol squat", kategoria: "Lower push", part: "s", coeff: 0.5, skokKg: 5.0, progresja: "asysta", uwagi: "UZUPEŁNIĆ – brak part/coeff w 4.0" },
  { id: "EX-0009", nazwa: "Banded pull ups", kategoria: "Upper pull vertical", part: "r", coeff: 0.75, skokKg: 5.0, progresja: "asysta", film: "https://youtu.be/5rR_bzBc1NA", scaloneId: "EX-0159" },
  { id: "EX-0010", nazwa: "Barbell back squat", kategoria: "Lower push", part: "s", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/rrJIyZGlK8c" },
  { id: "EX-0011", nazwa: "Barbell bench press", kategoria: "Upper push horizontal", part: "b", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/ejI1Nlsul9k", scaloneId: "EX-0021" },
  { id: "EX-0012", nazwa: "Barbell curl", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/N5x5M1x1Gd0", scaloneId: "EX-0023, EX-0024, EX-0025" },
  { id: "EX-0013", nazwa: "Barbell low bar squat", kategoria: "Lower push", part: "s", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/WYGyt6FdI78" },
  { id: "EX-0014", nazwa: "Barbell OHP", kategoria: "Upper push vertical", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/I7ND5OficOo" },
  { id: "EX-0015", nazwa: "Barbell oscilation", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0016", nazwa: "Barbell row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/bm0_q9bR_HA" },
  { id: "EX-0017", nazwa: "Barbell row dead stop pins", kategoria: "Upper pull horizontal", part: "r", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/qelbH7YGpms" },
  { id: "EX-0018", nazwa: "Barbell SLDL", kategoria: "Lower pull", part: "d", coeff: 0.25, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/lI8-igvsnVQ" },
  { id: "EX-0019", nazwa: "Bayesian curl", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/7sEMu6sxk9c" },
  { id: "EX-0020", nazwa: "Bear renegade row", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0022", nazwa: "Bench press paused 3sec", kategoria: "Upper push horizontal", part: "b", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/oE3cIMAWiUg" },
  { id: "EX-0029", nazwa: "Bicep hammer curl", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/RIEMoYL_h1Y", scaloneId: "EX-0033, EX-0096" },
  { id: "EX-0031", nazwa: "Bicep squat cable curl", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/PT0NBHQaQlk", scaloneId: "EX-0030, EX-0034" },
  { id: "EX-0035", nazwa: "Bird dog row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.5, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/IrMVMZoQum4" },
  { id: "EX-0036", nazwa: "Box jump", kategoria: "Lower push", part: "s", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0037", nazwa: "Bulgarian clean plyo", kategoria: "Lower pull", part: "d", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0038", nazwa: "Bulgarian squat assisted", kategoria: "Lower push", part: "s", coeff: 1.0, skokKg: 5.0, progresja: "asysta" },
  { id: "EX-0039", nazwa: "Cable biceps curl", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/RlkONM-NUvo" },
  { id: "EX-0040", nazwa: "Cable fly", kategoria: "Upper push horizontal", part: "b", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/hhruLxo9yZU" },
  { id: "EX-0041", nazwa: "Cable lateral raise s/a", kategoria: "Upper push vertical", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtube.com/shorts/lK-Jupl2ciQ", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0042", nazwa: "Cable row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/UCXxvVItLoM" },
  { id: "EX-0043", nazwa: "Cable row s/a", kategoria: "Upper pull horizontal", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/1Cfjgf2FBqc" },
  { id: "EX-0044", nazwa: "Calf raises", kategoria: "Lower push", part: "s", coeff: 0.25, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0045", nazwa: "Chest fly machine", kategoria: "Upper push horizontal", part: "b", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0046", nazwa: "Clean", kategoria: "Lower pull", part: "d", coeff: 1.0, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0047", nazwa: "Clean pins", kategoria: "Lower pull", part: "d", coeff: 0.75, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0048", nazwa: "Copenhagen plank", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 0.0, progresja: "czas", film: "https://youtu.be/Wv3O-CXt_YI" },
  { id: "EX-0049", nazwa: "Dead bug izo + OH", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/LomWOVw5QRA", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0050", nazwa: "Dead bug straight legs", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 0.0, progresja: "masa ciała", film: "https://youtube.com/shorts/wH1fFxR0v_s" },
  { id: "EX-0051", nazwa: "Dead stop barbell row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/zRu-zlvxgDA" },
  { id: "EX-0052", nazwa: "Deadbug OH", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/LomWOVw5QRA" },
  { id: "EX-0053", nazwa: "Deadlift", kategoria: "Lower pull", part: "d", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/AweC3UaM14o" },
  { id: "EX-0054", nazwa: "Deficit push up", kategoria: "Upper push horizontal", part: "b", coeff: 0.5, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/B68Foe2DkfI", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0055", nazwa: "Deficit reverse lunge", kategoria: "Lower push", part: "s", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/mTOMsoRLXl0" },
  { id: "EX-0056", nazwa: "Dips", kategoria: "Upper push horizontal", part: "b", coeff: 1.0, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/ebNGIOsFSe0", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0057", nazwa: "Dips weighted", kategoria: "Upper push horizontal", part: "b", coeff: 1.0, skokKg: 2.5, progresja: "dodatkowy ciężar", film: "https://youtube.com/shorts/HYqNyAx-32w" },
  { id: "EX-0059", nazwa: "Dumbbell bench press", kategoria: "Upper push horizontal", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/db-h-UBzbhE" },
  { id: "EX-0060", nazwa: "Dumbbell bench press alternating", kategoria: "Upper push horizontal", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/lXREuM-efRg" },
  { id: "EX-0061", nazwa: "Dumbbell curl", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/iixND1P2lik", scaloneId: "EX-0026, EX-0027, EX-0028, EX-0032" },
  { id: "EX-0062", nazwa: "Dumbbell external rotation", kategoria: "Upper pull horizontal", part: "r", coeff: 0.25, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/t5Ft8OMG_D8" },
  { id: "EX-0063", nazwa: "Dumbbell face down curl", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/jWKKcsAhZxc" },
  { id: "EX-0064", nazwa: "Dumbbell fly", kategoria: "Upper push horizontal", part: "b", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/JFm8KbhjibM", scaloneId: "EX-0065" },
  { id: "EX-0067", nazwa: "Dumbbell french press", kategoria: "Tricep", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/e3hmoAot--s" },
  { id: "EX-0069", nazwa: "Dumbbell lateral raise", kategoria: "Upper push vertical", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/XPPfnSEATJA", scaloneId: "EX-0070" },
  { id: "EX-0071", nazwa: "Dumbbell lunges", kategoria: "Lower push", part: "s", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/8fZxWTiIJWo" },
  { id: "EX-0073", nazwa: "Dumbbell OH press", kategoria: "Tricep", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/t7m6nASQcEI" },
  { id: "EX-0075", nazwa: "Dumbbell over head press", kategoria: "Upper push vertical", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/inBSVkTHeoY", scaloneId: "EX-0074" },
  { id: "EX-0076", nazwa: "Dumbbell over head press alternating", kategoria: "Upper push vertical", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/54kMlZMHenA" },
  { id: "EX-0077", nazwa: "Dumbbell row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/DMo3HJoawrU" },
  { id: "EX-0079", nazwa: "Dumbbell s/a Arnold press", kategoria: "Upper push vertical", part: "b", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/W-NAQSXMIO8" },
  { id: "EX-0080", nazwa: "Dumbbell s/a row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/ZRSGpBUVcNw", scaloneId: "EX-0078" },
  { id: "EX-0081", nazwa: "Dumbbell seal row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/zc-eFPRdPf0" },
  { id: "EX-0082", nazwa: "Dumbbells jumps", kategoria: "Lower push", part: "s", coeff: 0.75, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0083", nazwa: "Eccentric pull up", kategoria: "Upper pull vertical", part: "r", coeff: 0.75, skokKg: 0.0, progresja: "masa ciała", film: "https://youtube.com/shorts/TQ8h1VykMSw", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0084", nazwa: "Eccentric push up (5 sek w dół)", kategoria: "Upper push horizontal", part: "b", coeff: 0.5, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/Olkjnp6-2Rs" },
  { id: "EX-0085", nazwa: "Extensive plyo jumps s/l", kategoria: "Lower push", part: "s", coeff: 0.25, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0086", nazwa: "Ez bar curl", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtube.com/shorts/mwT2epCcwPo" },
  { id: "EX-0087", nazwa: "Facepull chest supported", kategoria: "Upper pull horizontal", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/tAp2J8tM6kw" },
  { id: "EX-0088", nazwa: "Front foot elevated split squat", kategoria: "Lower push", part: "s", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/6AetFa9S7x4" },
  { id: "EX-0089", nazwa: "Front squat", kategoria: "Lower push", part: "s", coeff: 1.0, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0090", nazwa: "GHD flexion", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0091", nazwa: "Glute bridge hamstrings izo + OH", kategoria: "Lower pull", part: "d", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/S4MbshcpwGE" },
  { id: "EX-0092", nazwa: "Glute crusher", kategoria: "Lower pull", part: "d", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/nV6qgZjPgPM" },
  { id: "EX-0093", nazwa: "Gorilla row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/ljzLtsz63YM" },
  { id: "EX-0094", nazwa: "Halfkneeling s/a cable pull", kategoria: "Upper pull vertical", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/H9pRHdfS5J4" },
  { id: "EX-0095", nazwa: "Halfkneeling wood chopper", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/Pn3UzUltqpA" },
  { id: "EX-0097", nazwa: "Hinged dumbbell row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/7AYVFgdmBF8" },
  { id: "EX-0100", nazwa: "Hip aeroplane", kategoria: "Lower pull", part: "d", coeff: 0.25, skokKg: 0.0, progresja: "ręczne ustawienie", film: "https://youtube.com/shorts/gbFNyOavleg" },
  { id: "EX-0101", nazwa: "Hip flexors cable", kategoria: "Lower push", part: "s", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0102", nazwa: "Hip thrust barbell", kategoria: "Lower pull", part: "d", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/5S8SApGU_Lk" },
  { id: "EX-0103", nazwa: "Hollow body + OH", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/tCXWI5XhV38", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0104", nazwa: "Horizontal jump", kategoria: "Lower push", part: "s", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0105", nazwa: "Incline bench lateral raise s/a", kategoria: "Upper push vertical", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/ZWhNCqMC41k", uwagi: "ZMIANA 5.0: było Upper pull vertical/r" },
  { id: "EX-0106", nazwa: "Incline curl + OHP", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg" },
  { id: "EX-0107", nazwa: "Incline dumbbell curl", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/aTYlqC_JacQ" },
  { id: "EX-0108", nazwa: "Incline dumbbell curl (back)", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/aG7CXiKxepw" },
  { id: "EX-0109", nazwa: "Incline dumbbell curl (front)", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/aDpreKl6uI4" },
  { id: "EX-0110", nazwa: "Incline dumbbell fly", kategoria: "Upper push horizontal", part: "b", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/JSDpq14vCZ8", scaloneId: "EX-0066" },
  { id: "EX-0111", nazwa: "Incline dumbbell press", kategoria: "Upper push horizontal", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/XdINt1ynflE", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff", scaloneId: "EX-0068" },
  { id: "EX-0112", nazwa: "Incline dumbbell press alternating", kategoria: "Upper push horizontal", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/-Wn61p9WoUk" },
  { id: "EX-0113", nazwa: "Incline sit-ups", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/DAnTf16NcT0" },
  { id: "EX-0114", nazwa: "Jefferson cable", kategoria: "Lower pull", part: "d", coeff: 0.25, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/N8gaQgvEYv0", scaloneId: "EX-0115" },
  { id: "EX-0117", nazwa: "Kettlebell march", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/a9tTen2zwuM" },
  { id: "EX-0118", nazwa: "Kickbacks", kategoria: "Lower pull", part: "d", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/qJxwJ1e1HxI" },
  { id: "EX-0120", nazwa: "Knee extension machine", kategoria: "Lower push", part: "s", coeff: 0.25, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/t8--Y-pjTmg", scaloneId: "EX-0119" },
  { id: "EX-0121", nazwa: "Knee flexion machine", kategoria: "Lower pull", part: "d", coeff: 0.25, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/nIj321YZWbo", uwagi: "ZMIANA 5.0: part s -> d (zgięcie kolana = tylna taśma)" },
  { id: "EX-0122", nazwa: "Knee raises", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 0.0, progresja: "masa ciała", film: "https://youtube.com/shorts/KBinYfCSs6s" },
  { id: "EX-0123", nazwa: "Landmine core", kategoria: "Core", part: "c", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/e5DP6961WEk" },
  { id: "EX-0124", nazwa: "Landmine press", kategoria: "Upper push vertical", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/029BoaFPp9U" },
  { id: "EX-0125", nazwa: "Landmine rotations (powtórzenia x2)", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/e5DP6961WEk", scaloneId: "EX-0126" },
  { id: "EX-0127", nazwa: "Landmine SLDL", kategoria: "Lower pull", part: "d", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/g_j67rzBERA" },
  { id: "EX-0128", nazwa: "Lat pulldown", kategoria: "Upper pull vertical", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/JGeRYIZdojU" },
  { id: "EX-0129", nazwa: "Lat pulldown behind the head", kategoria: "Upper pull vertical", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0130", nazwa: "Lat pulldown s/a", kategoria: "Upper pull vertical", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/X8lq6dZrr_s" },
  { id: "EX-0131", nazwa: "Lateral raise s/a", kategoria: "Upper push vertical", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtube.com/shorts/p8eMhRdeX4g" },
  { id: "EX-0132", nazwa: "Lateral raises", kategoria: "Upper push vertical", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/XPPfnSEATJA" },
  { id: "EX-0133", nazwa: "Lateral raises 2", kategoria: "Upper push vertical", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/OuG1smZTsQQ" },
  { id: "EX-0134", nazwa: "Lateral raises full ROM", kategoria: "Upper push vertical", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/4cOUa65oNjA", scaloneId: "EX-0135, EX-0136" },
  { id: "EX-0137", nazwa: "Lateral raises hinged", kategoria: "Upper push vertical", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/3BxRJkTjYkU", uwagi: "ZMIANA 5.0: part r -> b (ujednolicone z duplikatami)", scaloneId: "EX-0138, EX-0139" },
  { id: "EX-0140", nazwa: "Lateral raises incline s/a", kategoria: "Upper push vertical", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtube.com/shorts/dyCz4YlrmY8", scaloneId: "EX-0141" },
  { id: "EX-0142", nazwa: "Leg curl", kategoria: "Lower pull", part: "d", coeff: 0.25, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/SiwJ_T62l9c", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0143", nazwa: "Machine row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0144", nazwa: "Machine row s/a", kategoria: "Upper pull horizontal", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0145", nazwa: "Meadows row", kategoria: "Upper pull horizontal", part: "r", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/Pie3TyYQEQE", scaloneId: "EX-0072" },
  { id: "EX-0146", nazwa: "Med ball slam", kategoria: "Upper push horizontal", part: "b", coeff: 0.25, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/QxYhFwMd1Ks" },
  { id: "EX-0147", nazwa: "OH skullcrushers", kategoria: "Tricep", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg" },
  { id: "EX-0148", nazwa: "OHP barbell squat 15kg", kategoria: "Lower push", part: "s", coeff: 0.75, skokKg: 2.5, progresja: "kg", uwagi: "DO WERYFIKACJI – kategoria vs part" },
  { id: "EX-0149", nazwa: "Pistol squat eccentric", kategoria: "Lower push", part: "s", coeff: 0.5, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/mA2GWjqLn_k" },
  { id: "EX-0150", nazwa: "Plank contralateral", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 0.0, progresja: "czas", film: "https://youtu.be/-slYZChMfKE" },
  { id: "EX-0151", nazwa: "Plank dumbbell rotation", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 0.0, progresja: "czas", film: "https://youtu.be/HpEANSajJ1Q", scaloneId: "EX-0152" },
  { id: "EX-0153", nazwa: "Plank leg raises", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 0.0, progresja: "czas", film: "https://youtu.be/Akf3IP0H9fA" },
  { id: "EX-0154", nazwa: "Poliquin step up", kategoria: "Lower push", part: "s", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/hURHPjerxtc" },
  { id: "EX-0155", nazwa: "Poliquin step up paused 3sec", kategoria: "Lower push", part: "s", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/hURHPjerxtc" },
  { id: "EX-0156", nazwa: "Pronation/Supination", kategoria: "Bicep", part: "r", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtube.com/shorts/F8UKIhHfVnE", scaloneId: "EX-0157" },
  { id: "EX-0158", nazwa: "Pull up", kategoria: "Upper pull vertical", part: "r", coeff: 0.75, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/k7zWqAo0ITw", scaloneId: "EX-0163" },
  { id: "EX-0160", nazwa: "Pull up eccentric weighted", kategoria: "Upper pull vertical", part: "r", coeff: 1.0, skokKg: 2.5, progresja: "dodatkowy ciężar", film: "https://youtu.be/2FUHizTAu30", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0161", nazwa: "Pull up eccentric weighted (5 sek w dół)", kategoria: "Upper pull vertical", part: "r", coeff: 0.75, skokKg: 2.5, progresja: "dodatkowy ciężar", film: "https://youtu.be/2FUHizTAu30" },
  { id: "EX-0162", nazwa: "Pull up weighted", kategoria: "Upper pull vertical", part: "r", coeff: 1.0, skokKg: 2.5, progresja: "dodatkowy ciężar", film: "https://youtube.com/shorts/qwXUU0JPYnY" },
  { id: "EX-0164", nazwa: "Pull ups (paused)", kategoria: "Upper pull vertical", part: "r", coeff: 0.75, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/Z1TSHG8txCA" },
  { id: "EX-0165", nazwa: "Push press barbell", kategoria: "Upper push vertical", part: "b", coeff: 1.0, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0166", nazwa: "Push up", kategoria: "Upper push horizontal", part: "b", coeff: 0.5, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/WDIpL0pjun0" },
  { id: "EX-0167", nazwa: "Raised bird dog", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 0.0, progresja: "masa ciała", film: "https://youtube.com/shorts/eMc71nTlciE" },
  { id: "EX-0168", nazwa: "RDL", kategoria: "Lower pull", part: "d", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/bT5OOBgY4bc" },
  { id: "EX-0169", nazwa: "Reverse Nordic", kategoria: "Lower push", part: "s", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/GbpDfXXKuk0" },
  { id: "EX-0170", nazwa: "Rope pushdown", kategoria: "Tricep", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/-xa-6cQaZKY" },
  { id: "EX-0171", nazwa: "Rope pushdown OH", kategoria: "Tricep", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/kqidUIf1eJE" },
  { id: "EX-0172", nazwa: "S/a cable pulldown incline bench", kategoria: "Upper pull vertical", part: "r", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/jZJwvnIGfnE" },
  { id: "EX-0173", nazwa: "S/a lat pulldown incline bench", kategoria: "Upper pull vertical", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/Jfod5GrRtsQ" },
  { id: "EX-0174", nazwa: "S/l dragonflag eccentric", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/fL2C8V9-GVE" },
  { id: "EX-0175", nazwa: "S/l hip thrust", kategoria: "Lower pull", part: "d", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/hKXqCXSXylA" },
  { id: "EX-0176", nazwa: "Seated broad jump", kategoria: "Lower push", part: "s", coeff: 0.25, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/VfeSIznmgPM" },
  { id: "EX-0177", nazwa: "Seated cable facepull", kategoria: "Upper pull horizontal", part: "r", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/EFNCtZZDA-A", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0178", nazwa: "Seated seesaw press (nogi proste)", kategoria: "Upper push vertical", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/_tXELZW_GC0" },
  { id: "EX-0179", nazwa: "Seesaw press", kategoria: "Upper push vertical", part: "b", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/-Zn-qALpVR0", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0180", nazwa: "Side crunches", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 0.0, progresja: "masa ciała", film: "https://youtu.be/6B0h913kbbk", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0181", nazwa: "Side plank hip drop", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 0.0, progresja: "czas", film: "https://youtube.com/shorts/kqwm4S7rCMY" },
  { id: "EX-0182", nazwa: "Side plank rotations", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 0.0, progresja: "czas", film: "https://youtu.be/OMc5f_JUDUU" },
  { id: "EX-0183", nazwa: "SLDL balance", kategoria: "Lower pull", part: "d", coeff: 0.25, skokKg: 0.0, progresja: "ręczne ustawienie", film: "https://youtu.be/lI8-igvsnVQ" },
  { id: "EX-0184", nazwa: "Split squat", kategoria: "Lower push", part: "s", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/hXpGSa5HYqY" },
  { id: "EX-0185", nazwa: "Split stance SLDL", kategoria: "Lower pull", part: "d", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/G4Gr_3Wl-Ms" },
  { id: "EX-0186", nazwa: "Squat izo (15 sek)", kategoria: "Lower push", part: "s", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/krhx426rjU8" },
  { id: "EX-0187", nazwa: "Standing landmine press", kategoria: "Upper push vertical", part: "b", coeff: 0.75, skokKg: 2.5, progresja: "kg" },
  { id: "EX-0188", nazwa: "Suitcase carry", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 0.0, progresja: "dystans", film: "https://youtu.be/51gqdYyaqUQ" },
  { id: "EX-0189", nazwa: "Supine pigeon abs", kategoria: "Core", part: "c", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/K4Gu8YL1fDc" },
  { id: "EX-0190", nazwa: "Swiss ball leg curl", kategoria: "Lower pull", part: "d", coeff: 0.75, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/xB1lGVzRwWk" },
  { id: "EX-0191", nazwa: "Toes to bar", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/xX9Hzi7Onnw" },
  { id: "EX-0192", nazwa: "Trap bar deadlift", kategoria: "Lower pull", part: "d", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/v709aJKv-gM", uwagi: "DO WERYFIKACJI – konflikt category/part/coeff" },
  { id: "EX-0194", nazwa: "Tricep cable pushdown", kategoria: "Tricep", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/LXkCrxn3caQ", scaloneId: "EX-0198, EX-0200" },
  { id: "EX-0195", nazwa: "Tricep JM press", kategoria: "Tricep", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/Tih5iHyELsE", scaloneId: "EX-0116" },
  { id: "EX-0196", nazwa: "Tricep OH cable", kategoria: "Tricep", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtu.be/1u18yJELsh0", scaloneId: "EX-0193" },
  { id: "EX-0197", nazwa: "Tricep OH ez bar", kategoria: "Tricep", part: "b", coeff: 0.25, skokKg: 1.0, progresja: "kg", film: "https://youtube.com/shorts/tXPrecaYeJ8", scaloneId: "EX-0199" },
  { id: "EX-0201", nazwa: "Walking lunges", kategoria: "Lower push", part: "s", coeff: 1.0, skokKg: 2.5, progresja: "kg", film: "https://youtu.be/8fZxWTiIJWo" },
  { id: "EX-0202", nazwa: "Wipers kettle", kategoria: "Core", part: "c", coeff: 0.5, skokKg: 2.5, progresja: "kg", film: "https://youtube.com/shorts/_EwxIRjkYy4" },
  { id: "EX-0203", nazwa: "Zercher jumps", kategoria: "Lower push", part: "s", coeff: 0.5, skokKg: 2.5, progresja: "kg", uwagi: "UZUPEŁNIĆ – brak part/coeff w 4.0" },
];
