// PLIK GENEROWANY — nie edytuj recznie.
// Zrodlo: docs/dane/szablony-base44.json + szkielety-base44.json (Base44, 21.09.2026)
// Regeneracja: python3 silnik/narzedzia/generuj-dane.py

import type { SzablonPlanu } from "../szablony-planow.ts";

/** 14 szablonow z aplikacji trenera w Base44. */
export const SZABLONY_BASE44: readonly SzablonPlanu[] = [
  {
    id: "fbw_3dni_6w", nazwa: "FBW 3 dni – 3 główne ćwiczenia",
    opis: "3 dni/tydz. · 6-tygodniowy blok · 3 główne wzorce ruchowe (Push/Pull/Nogi)",
    czesc: "objętość", zCwiczeniami: true,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true, cwiczenieId: "EX-0011" },
      { lp: "B1.", kategoria: "Lower push", cwiczenieId: "EX-0010" },
      { lp: "B2.", kategoria: "Lower pull", cwiczenieId: "EX-0053" },
      { lp: "C1.", kategoria: "Upper pull horizontal", cwiczenieId: "EX-0016" },
      { lp: "C2.", kategoria: "Tricep", bezOdpowiednika: "Close-Grip Bench Press" },
      { lp: "D1.", kategoria: "Core", bezOdpowiednika: "Plank" },
      { lp: "D2.", kategoria: "Upper push vertical", cwiczenieId: "EX-0014" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push", topSet: true, cwiczenieId: "EX-0010" },
      { lp: "B1.", kategoria: "Upper pull horizontal", cwiczenieId: "EX-0016" },
      { lp: "B2.", kategoria: "Upper push horizontal", cwiczenieId: "EX-0011" },
      { lp: "C1.", kategoria: "Lower pull", cwiczenieId: "EX-0053" },
      { lp: "C2.", kategoria: "Core", bezOdpowiednika: "Plank" },
      { lp: "D1.", kategoria: "Bicep", cwiczenieId: "EX-0012" },
      { lp: "D2.", kategoria: "Upper push vertical", cwiczenieId: "EX-0014" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true, cwiczenieId: "EX-0053" },
      { lp: "B1.", kategoria: "Upper push vertical", cwiczenieId: "EX-0014" },
      { lp: "B2.", kategoria: "Upper pull vertical", cwiczenieId: "EX-0158" },
      { lp: "C1.", kategoria: "Lower push", cwiczenieId: "EX-0010" },
      { lp: "C2.", kategoria: "Core", bezOdpowiednika: "Plank" },
      { lp: "D1.", kategoria: "Bicep", cwiczenieId: "EX-0012" },
      { lp: "D2.", kategoria: "Tricep", bezOdpowiednika: "Close-Grip Bench Press" },
    ],
    ],
  },
  {
    id: "fbw_6cwiczen_6w", nazwa: "FBW 6 ćwiczeń złożonych",
    opis: "3 dni/tydz. · 6-tygodniowy blok · 6 głównych ćwiczeń złożonych (2 per dzień)",
    czesc: "objętość", zCwiczeniami: false,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Lower pull" },
      { lp: "D1.", kategoria: "Upper pull horizontal" },
      { lp: "D2.", kategoria: "Tricep" },
      { lp: "E1.", kategoria: "Core" },
      { lp: "E2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Upper pull horizontal" },
      { lp: "D1.", kategoria: "Lower pull" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Upper push vertical" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Lower push" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Tricep" },
    ],
    ],
  },
  {
    id: "fbw_2dni_6w", nazwa: "FBW 2 dni – 3 główne ćwiczenia",
    opis: "2 dni/tydz. · 6-tygodniowy blok · 3 główne wzorce ruchowe (Push/Pull/Nogi)",
    czesc: "objętość", zCwiczeniami: false,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Tricep" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper pull vertical" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Tricep" },
    ],
    ],
  },
  {
    id: "fbw_2dni_6cwiczen_6w", nazwa: "FBW 2 dni – 6 ćwiczeń złożonych",
    opis: "2 dni/tydz. · 6-tygodniowy blok · 6 głównych ćwiczeń złożonych (2 per sesja)",
    czesc: "objętość", zCwiczeniami: true,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true, cwiczenieId: "EX-0011" },
      { lp: "B1.", kategoria: "Lower push", cwiczenieId: "EX-0010" },
      { lp: "C1.", kategoria: "Lower push", cwiczenieId: "EX-0010" },
      { lp: "C2.", kategoria: "Lower pull", cwiczenieId: "EX-0053" },
      { lp: "D1.", kategoria: "Upper pull horizontal", cwiczenieId: "EX-0016" },
      { lp: "D2.", kategoria: "Tricep", bezOdpowiednika: "Close-Grip Bench Press" },
      { lp: "E1.", kategoria: "Core", bezOdpowiednika: "Plank" },
      { lp: "E2.", kategoria: "Upper push vertical", cwiczenieId: "EX-0014" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true, cwiczenieId: "EX-0053" },
      { lp: "B1.", kategoria: "Upper push horizontal", cwiczenieId: "EX-0011" },
      { lp: "C1.", kategoria: "Upper push vertical", cwiczenieId: "EX-0014" },
      { lp: "C2.", kategoria: "Upper pull vertical", cwiczenieId: "EX-0158" },
      { lp: "D1.", kategoria: "Lower push", cwiczenieId: "EX-0010" },
      { lp: "D2.", kategoria: "Core", bezOdpowiednika: "Plank" },
      { lp: "E1.", kategoria: "Bicep", cwiczenieId: "EX-0012" },
      { lp: "E2.", kategoria: "Tricep", bezOdpowiednika: "Close-Grip Bench Press" },
    ],
    ],
  },
  {
    id: "fbw_3dni_6w_v2", nazwa: "FBW 3 dni – 3 główne ćwiczenia (część 2)",
    opis: "3 dni/tydz. · 6-tygodniowy blok · 3 główne wzorce ruchowe · zakres 6-8 / 8-10 powt. dla akcesorii",
    czesc: "intensywność", zCwiczeniami: false,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Tricep" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push", topSet: true },
      { lp: "B1.", kategoria: "Upper pull horizontal" },
      { lp: "B2.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper pull vertical" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Tricep" },
    ],
    ],
  },
  {
    id: "fbw_2dni_6w_v2", nazwa: "FBW 2 dni – 3 główne ćwiczenia (część 2)",
    opis: "2 dni/tydz. · 6-tygodniowy blok · zakres 6-8 / 8-10 powt. dla akcesorii",
    czesc: "intensywność", zCwiczeniami: false,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Tricep" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper pull vertical" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Tricep" },
    ],
    ],
  },
  {
    id: "fbw_4dni_6w", nazwa: "FBW 4 dni – 4 główne ćwiczenia",
    opis: "4 dni/tydz. · 6-tygodniowy blok · 4 główne wzorce ruchowe (Push H / Lower Push / Lower Pull / Pull H)",
    czesc: "objętość", zCwiczeniami: true,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true, cwiczenieId: "EX-0011" },
      { lp: "B1.", kategoria: "Lower push", cwiczenieId: "EX-0010" },
      { lp: "B2.", kategoria: "Lower pull", cwiczenieId: "EX-0053" },
      { lp: "C1.", kategoria: "Upper pull horizontal", cwiczenieId: "EX-0016" },
      { lp: "C2.", kategoria: "Tricep", bezOdpowiednika: "Close-Grip Bench Press" },
      { lp: "D1.", kategoria: "Core", bezOdpowiednika: "Plank" },
      { lp: "D2.", kategoria: "Upper push vertical", cwiczenieId: "EX-0014" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push", topSet: true, cwiczenieId: "EX-0010" },
      { lp: "B1.", kategoria: "Upper pull horizontal", cwiczenieId: "EX-0016" },
      { lp: "B2.", kategoria: "Upper push horizontal", cwiczenieId: "EX-0011" },
      { lp: "C1.", kategoria: "Lower pull", cwiczenieId: "EX-0053" },
      { lp: "C2.", kategoria: "Core", bezOdpowiednika: "Plank" },
      { lp: "D1.", kategoria: "Bicep", cwiczenieId: "EX-0012" },
      { lp: "D2.", kategoria: "Upper push vertical", cwiczenieId: "EX-0014" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true, cwiczenieId: "EX-0053" },
      { lp: "B1.", kategoria: "Upper push vertical", cwiczenieId: "EX-0014" },
      { lp: "B2.", kategoria: "Upper pull vertical", cwiczenieId: "EX-0158" },
      { lp: "C1.", kategoria: "Lower push", cwiczenieId: "EX-0010" },
      { lp: "C2.", kategoria: "Core", bezOdpowiednika: "Plank" },
      { lp: "D1.", kategoria: "Bicep", cwiczenieId: "EX-0012" },
      { lp: "D2.", kategoria: "Tricep", bezOdpowiednika: "Close-Grip Bench Press" },
    ],
    [
      { lp: "A1.", kategoria: "Upper pull horizontal", topSet: true, cwiczenieId: "EX-0016" },
      { lp: "B1.", kategoria: "Upper push vertical", cwiczenieId: "EX-0014" },
      { lp: "B2.", kategoria: "Lower pull", cwiczenieId: "EX-0053" },
      { lp: "C1.", kategoria: "Upper pull vertical", cwiczenieId: "EX-0158" },
      { lp: "C2.", kategoria: "Bicep", cwiczenieId: "EX-0012" },
      { lp: "D1.", kategoria: "Core", bezOdpowiednika: "Plank" },
      { lp: "D2.", kategoria: "Upper push horizontal", cwiczenieId: "EX-0011" },
    ],
    ],
  },
  {
    id: "fbw_1dzien_6w", nazwa: "FBW 1 dzień – pełne ciało",
    opis: "1 dzień/tydz. · 6-tygodniowy blok · pełne ciało w jednej sesji",
    czesc: "objętość", zCwiczeniami: false,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    ],
  },
  {
    id: "fbw_4dni_6cwiczen_6w", nazwa: "FBW Rozbudowany 4 dni",
    opis: "4 dni/tydz. · 6-tygodniowy blok · 8 ćwiczeń złożonych (2 per dzień)",
    czesc: "objętość", zCwiczeniami: false,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Lower pull" },
      { lp: "D1.", kategoria: "Upper pull horizontal" },
      { lp: "D2.", kategoria: "Tricep" },
      { lp: "E1.", kategoria: "Core" },
      { lp: "E2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Upper pull horizontal" },
      { lp: "D1.", kategoria: "Lower pull" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Upper push vertical" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Lower push" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Tricep" },
    ],
    [
      { lp: "A1.", kategoria: "Upper pull horizontal", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Lower push" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Upper push horizontal" },
    ],
    ],
  },
  {
    id: "fbw_1dzien_6cwiczen_6w", nazwa: "FBW Rozbudowany 1 dzień",
    opis: "1 dzień/tydz. · 6-tygodniowy blok · pełne ciało, 2 główne ćwiczenia złożone",
    czesc: "objętość", zCwiczeniami: true,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true, cwiczenieId: "EX-0011" },
      { lp: "B1.", kategoria: "Lower push", cwiczenieId: "EX-0010" },
      { lp: "C1.", kategoria: "Lower pull", cwiczenieId: "EX-0053" },
      { lp: "C2.", kategoria: "Upper pull horizontal", cwiczenieId: "EX-0042" },
      { lp: "D1.", kategoria: "Upper pull vertical", cwiczenieId: "EX-0158" },
      { lp: "D2.", kategoria: "Core", bezOdpowiednika: "Plank" },
      { lp: "E1.", kategoria: "Bicep", cwiczenieId: "EX-0012" },
      { lp: "E2.", kategoria: "Upper push vertical", bezOdpowiednika: "Machine Shoulder Press" },
    ],
    ],
  },
  {
    id: "hyper_1dzien_6w", nazwa: "Hipertroficzny 1 dzień",
    opis: "1 dzień/tydz. · 6-tygodniowy blok · pełne ciało, 9 slotów akcesoryjnych",
    czesc: "hipertrofia", zCwiczeniami: false,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal" },
      { lp: "A2.", kategoria: "Upper push vertical" },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Tricep" },
      { lp: "E1.", kategoria: "Core" },
    ],
    ],
  },
  {
    id: "hyper_2dni_6w", nazwa: "Hipertroficzny 2 dni",
    opis: "2 dni/tydz. · 6-tygodniowy blok · Push/Pull split, 7 slotów/dzień",
    czesc: "hipertrofia", zCwiczeniami: false,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal" },
      { lp: "A2.", kategoria: "Upper push vertical" },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower push" },
      { lp: "C1.", kategoria: "Tricep" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Upper push horizontal" },
    ],
    [
      { lp: "A1.", kategoria: "Upper pull horizontal" },
      { lp: "A2.", kategoria: "Upper pull vertical" },
      { lp: "B1.", kategoria: "Lower pull" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Bicep" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Upper pull horizontal" },
    ],
    ],
  },
  {
    id: "hyper_3dni_6w", nazwa: "Hipertroficzny 3 dni",
    opis: "3 dni/tydz. · 6-tygodniowy blok · Push/Pull/Legs split",
    czesc: "hipertrofia", zCwiczeniami: false,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal" },
      { lp: "A2.", kategoria: "Upper push horizontal" },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper push vertical" },
      { lp: "C1.", kategoria: "Tricep" },
      { lp: "C2.", kategoria: "Tricep" },
    ],
    [
      { lp: "A1.", kategoria: "Upper pull horizontal" },
      { lp: "A2.", kategoria: "Upper pull horizontal" },
      { lp: "B1.", kategoria: "Upper pull vertical" },
      { lp: "B2.", kategoria: "Upper pull vertical" },
      { lp: "C1.", kategoria: "Bicep" },
      { lp: "C2.", kategoria: "Bicep" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push" },
      { lp: "A2.", kategoria: "Lower push" },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Core" },
    ],
    ],
  },
  {
    id: "hyper_4dni_6w", nazwa: "Hipertroficzny 4 dni",
    opis: "4 dni/tydz. · 6-tygodniowy blok · Upper Push / Upper Pull / Lower / Arms+Core",
    czesc: "hipertrofia", zCwiczeniami: false,
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal" },
      { lp: "A2.", kategoria: "Upper push horizontal" },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Tricep" },
      { lp: "C2.", kategoria: "Upper push vertical" },
      { lp: "D1.", kategoria: "Tricep" },
    ],
    [
      { lp: "A1.", kategoria: "Upper pull horizontal" },
      { lp: "A2.", kategoria: "Upper pull horizontal" },
      { lp: "B1.", kategoria: "Upper pull vertical" },
      { lp: "B2.", kategoria: "Upper pull horizontal" },
      { lp: "C1.", kategoria: "Bicep" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Bicep" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push" },
      { lp: "A2.", kategoria: "Lower push" },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower push" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Lower pull" },
      { lp: "D1.", kategoria: "Lower pull" },
      { lp: "D2.", kategoria: "Core" },
    ],
    [
      { lp: "A1.", kategoria: "Bicep" },
      { lp: "A2.", kategoria: "Bicep" },
      { lp: "B1.", kategoria: "Tricep" },
      { lp: "B2.", kategoria: "Tricep" },
      { lp: "C1.", kategoria: "Core" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Upper push horizontal" },
    ],
    ],
  },
];
