// PLIK GENEROWANY — nie edytuj recznie.
// Zrodlo: docs/dane/szablony-base44.json + rodziny-szablonow-base44.json (Base44)
// Regeneracja: python3 silnik/narzedzia/generuj-dane.py

import type { SzablonPlanu } from "../szablony-planow.ts";

/** 14 szablonow z aplikacji trenera w Base44, w kolejnosci z jej ekranu. */
export const SZABLONY_BASE44: readonly SzablonPlanu[] = [
  {
    id: "fbw_1dzien_6w", nazwa: "Klasyczny – 1 dzień",
    rodzina: "Klasyczny",
    opis: "Zrównoważone proporcje siły i masy. Główne ćwiczenia złożone z progresją RPE. 1 dzień/tydz. · 6-tygodniowy blok · pełne ciało w jednej sesji",
    czesc: "objętość",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    ],
  },
  {
    id: "fbw_2dni_6w", nazwa: "Klasyczny – 2 dni",
    rodzina: "Klasyczny",
    opis: "Zrównoważone proporcje siły i masy. Główne ćwiczenia złożone z progresją RPE. 2 dni/tydz. · 6-tygodniowy blok · 3 główne wzorce ruchowe (Push/Pull/Nogi)",
    czesc: "objętość",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Tricep" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper pull vertical" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Tricep" },
    ],
    ],
  },
  {
    id: "fbw_3dni_6w", nazwa: "Klasyczny – 3 dni",
    rodzina: "Klasyczny",
    opis: "Zrównoważone proporcje siły i masy. Główne ćwiczenia złożone z progresją RPE. 3 dni/tydz. · 6-tygodniowy blok · 3 główne wzorce ruchowe (Push/Pull/Nogi)",
    czesc: "objętość",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Tricep" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push", topSet: true },
      { lp: "B1.", kategoria: "Upper pull horizontal" },
      { lp: "B2.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper pull vertical" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Tricep" },
    ],
    ],
  },
  {
    id: "fbw_4dni_6w", nazwa: "Klasyczny – 4 dni",
    rodzina: "Klasyczny",
    opis: "Zrównoważone proporcje siły i masy. Główne ćwiczenia złożone z progresją RPE. 4 dni/tydz. · 6-tygodniowy blok · 4 główne wzorce ruchowe (Push H / Lower Push / Lower Pull / Pull H)",
    czesc: "objętość",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Tricep" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push", topSet: true },
      { lp: "B1.", kategoria: "Upper pull horizontal" },
      { lp: "B2.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper pull vertical" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Tricep" },
    ],
    [
      { lp: "A1.", kategoria: "Upper pull horizontal", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull vertical" },
      { lp: "C2.", kategoria: "Bicep" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push horizontal" },
    ],
    ],
  },
  {
    id: "fbw_1dzien_6cwiczen_6w", nazwa: "Rozbudowany – 1 dzień",
    rodzina: "Rozbudowany",
    opis: "Wyższy nacisk na siłę. Więcej ćwiczeń złożonych, wyższe RPE, cięższe sesje. 1 dzień/tydz. · 6-tygodniowy blok · pełne ciało, 2 główne ćwiczenia złożone",
    czesc: "objętość",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Upper pull horizontal" },
      { lp: "D1.", kategoria: "Upper pull vertical" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Upper push vertical" },
    ],
    ],
  },
  {
    id: "fbw_2dni_6cwiczen_6w", nazwa: "Rozbudowany – 2 dni",
    rodzina: "Rozbudowany",
    opis: "Wyższy nacisk na siłę. Więcej ćwiczeń złożonych, wyższe RPE, cięższe sesje. 2 dni/tydz. · 6-tygodniowy blok · 6 głównych ćwiczeń złożonych (2 per sesja)",
    czesc: "objętość",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Lower pull" },
      { lp: "D1.", kategoria: "Upper pull horizontal" },
      { lp: "D2.", kategoria: "Tricep" },
      { lp: "E1.", kategoria: "Core" },
      { lp: "E2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Upper push vertical" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Lower push" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Tricep" },
    ],
    ],
  },
  {
    id: "fbw_6cwiczen_6w", nazwa: "Rozbudowany – 3 dni",
    rodzina: "Rozbudowany",
    opis: "Wyższy nacisk na siłę. Więcej ćwiczeń złożonych, wyższe RPE, cięższe sesje. 3 dni/tydz. · 6-tygodniowy blok · 6 głównych ćwiczeń złożonych (2 per dzień)",
    czesc: "objętość",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Lower pull" },
      { lp: "D1.", kategoria: "Upper pull horizontal" },
      { lp: "D2.", kategoria: "Tricep" },
      { lp: "E1.", kategoria: "Core" },
      { lp: "E2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Upper pull horizontal" },
      { lp: "D1.", kategoria: "Lower pull" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Upper push vertical" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Lower push" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Tricep" },
    ],
    ],
  },
  {
    id: "fbw_4dni_6cwiczen_6w", nazwa: "Rozbudowany – 4 dni",
    rodzina: "Rozbudowany",
    opis: "Wyższy nacisk na siłę. Więcej ćwiczeń złożonych, wyższe RPE, cięższe sesje. 4 dni/tydz. · 6-tygodniowy blok · 8 ćwiczeń złożonych (2 per dzień)",
    czesc: "objętość",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Lower pull" },
      { lp: "D1.", kategoria: "Upper pull horizontal" },
      { lp: "D2.", kategoria: "Tricep" },
      { lp: "E1.", kategoria: "Core" },
      { lp: "E2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Upper pull horizontal" },
      { lp: "D1.", kategoria: "Lower pull" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Upper push vertical" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Lower push" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Tricep" },
    ],
    [
      { lp: "A1.", kategoria: "Upper pull horizontal", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Lower push" },
      { lp: "D2.", kategoria: "Core" },
      { lp: "E1.", kategoria: "Bicep" },
      { lp: "E2.", kategoria: "Upper push horizontal" },
    ],
    ],
  },
  {
    id: "hyper_1dzien_6w", nazwa: "Hipertroficzny – 1 dzień",
    rodzina: "Hipertroficzny",
    opis: "Skupiony na masie mięśniowej. Wyższy zakres powtórzeń (12–15), więcej serii per partia. 1 dzień/tydz. · 6-tygodniowy blok · pełne ciało, 9 slotów akcesoryjnych",
    czesc: "hipertrofia",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal" },
      { lp: "A2.", kategoria: "Upper push vertical" },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Tricep" },
      { lp: "E1.", kategoria: "Core" },
    ],
    ],
  },
  {
    id: "hyper_2dni_6w", nazwa: "Hipertroficzny – 2 dni",
    rodzina: "Hipertroficzny",
    opis: "Skupiony na masie mięśniowej. Wyższy zakres powtórzeń (12–15), więcej serii per partia. 2 dni/tydz. · 6-tygodniowy blok · Push/Pull split, 7 slotów/dzień",
    czesc: "hipertrofia",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal" },
      { lp: "A2.", kategoria: "Upper push vertical" },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower push" },
      { lp: "C1.", kategoria: "Tricep" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Upper push horizontal" },
    ],
    [
      { lp: "A1.", kategoria: "Upper pull horizontal" },
      { lp: "A2.", kategoria: "Upper pull vertical" },
      { lp: "B1.", kategoria: "Lower pull" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Bicep" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Upper pull horizontal" },
    ],
    ],
  },
  {
    id: "hyper_3dni_6w", nazwa: "Hipertroficzny – 3 dni",
    rodzina: "Hipertroficzny",
    opis: "Skupiony na masie mięśniowej. Wyższy zakres powtórzeń (12–15), więcej serii per partia. 3 dni/tydz. · 6-tygodniowy blok · Push/Pull/Legs split",
    czesc: "hipertrofia",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal" },
      { lp: "A2.", kategoria: "Upper push horizontal" },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper push vertical" },
      { lp: "C1.", kategoria: "Tricep" },
      { lp: "C2.", kategoria: "Tricep" },
    ],
    [
      { lp: "A1.", kategoria: "Upper pull horizontal" },
      { lp: "A2.", kategoria: "Upper pull horizontal" },
      { lp: "B1.", kategoria: "Upper pull vertical" },
      { lp: "B2.", kategoria: "Upper pull vertical" },
      { lp: "C1.", kategoria: "Bicep" },
      { lp: "C2.", kategoria: "Bicep" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push" },
      { lp: "A2.", kategoria: "Lower push" },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Core" },
    ],
    ],
  },
  {
    id: "hyper_4dni_6w", nazwa: "Hipertroficzny – 4 dni",
    rodzina: "Hipertroficzny",
    opis: "Skupiony na masie mięśniowej. Wyższy zakres powtórzeń (12–15), więcej serii per partia. 4 dni/tydz. · 6-tygodniowy blok · Upper Push / Upper Pull / Lower / Arms+Core",
    czesc: "hipertrofia",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal" },
      { lp: "A2.", kategoria: "Upper push horizontal" },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Tricep" },
      { lp: "C2.", kategoria: "Upper push vertical" },
      { lp: "D1.", kategoria: "Tricep" },
    ],
    [
      { lp: "A1.", kategoria: "Upper pull horizontal" },
      { lp: "A2.", kategoria: "Upper pull horizontal" },
      { lp: "B1.", kategoria: "Upper pull vertical" },
      { lp: "B2.", kategoria: "Upper pull horizontal" },
      { lp: "C1.", kategoria: "Bicep" },
      { lp: "C2.", kategoria: "Upper pull vertical" },
      { lp: "D1.", kategoria: "Bicep" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push" },
      { lp: "A2.", kategoria: "Lower push" },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower push" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Lower pull" },
      { lp: "D1.", kategoria: "Lower pull" },
      { lp: "D2.", kategoria: "Core" },
    ],
    [
      { lp: "A1.", kategoria: "Bicep" },
      { lp: "A2.", kategoria: "Bicep" },
      { lp: "B1.", kategoria: "Tricep" },
      { lp: "B2.", kategoria: "Tricep" },
      { lp: "C1.", kategoria: "Core" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Upper push horizontal" },
    ],
    ],
  },
  {
    id: "fbw_2dni_6w_v2", nazwa: "Klasyczny – 2 dni (cz. 2)",
    rodzina: "Kontynuacje (cz. 2)",
    opis: "Kontynuacja bloku Klasycznego. Wyższe RPE, przesunięty zakres powtórzeń. 2 dni/tydz. · 6-tygodniowy blok · zakres 6-8 / 8-10 powt. dla akcesorii",
    czesc: "intensywność",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Tricep" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper pull vertical" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Tricep" },
    ],
    ],
  },
  {
    id: "fbw_3dni_6w_v2", nazwa: "Klasyczny – 3 dni (cz. 2)",
    rodzina: "Kontynuacje (cz. 2)",
    opis: "Kontynuacja bloku Klasycznego. Wyższe RPE, przesunięty zakres powtórzeń. 3 dni/tydz. · 6-tygodniowy blok · 3 główne wzorce ruchowe · zakres 6-8 / 8-10 powt. dla akcesorii",
    czesc: "intensywność",
    dni: [
    [
      { lp: "A1.", kategoria: "Upper push horizontal", topSet: true },
      { lp: "B1.", kategoria: "Lower push" },
      { lp: "B2.", kategoria: "Lower pull" },
      { lp: "C1.", kategoria: "Upper pull horizontal" },
      { lp: "C2.", kategoria: "Tricep" },
      { lp: "D1.", kategoria: "Core" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower push", topSet: true },
      { lp: "B1.", kategoria: "Upper pull horizontal" },
      { lp: "B2.", kategoria: "Upper push horizontal" },
      { lp: "C1.", kategoria: "Lower pull" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Upper push vertical" },
    ],
    [
      { lp: "A1.", kategoria: "Lower pull", topSet: true },
      { lp: "B1.", kategoria: "Upper push vertical" },
      { lp: "B2.", kategoria: "Upper pull vertical" },
      { lp: "C1.", kategoria: "Lower push" },
      { lp: "C2.", kategoria: "Core" },
      { lp: "D1.", kategoria: "Bicep" },
      { lp: "D2.", kategoria: "Tricep" },
    ],
    ],
  },
];
